[package]
name = "urlencode"
version = "0.1.0"
authors = ["Vadim Polulyakh <bavadim@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
urlencoding = "1.1.1"